version: '3'
services:
  app:
    image: node:8.16.2-alpine
    user: node
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - HOST=0.0.0.0
    working_dir: /application
    volumes:
      - .:/application:cached
    command: >
      sh -c "yarn install && yarn start"
